# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: testapp
        image: testapp # here add your image url or name with tag
        ports:
        - containerPort: 8000
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: testapp-service
spec:
  selector:
    app: testapp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort  # Use 'NodePort' or 'ClusterIP' if not using a cloud provider with LoadBalancer support
